# Generated by Django 2.1.8 on 2019-04-16 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dir', models.CharField(default='dirImage', max_length=256)),
                ('name', models.CharField(default='nameImage', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date(2019, 4, 16), verbose_name='Date')),
                ('name', models.CharField(default='dataSetName', max_length=100)),
                ('desc', models.CharField(default='dataSetDesc', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idDataSet', models.IntegerField(default=1)),
                ('dir', models.CharField(default='dirImage', max_length=256)),
                ('name', models.CharField(default='nameImage', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dir', models.CharField(default='dirImage', max_length=256)),
                ('name', models.CharField(default='nameImage', max_length=256)),
                ('idDataSet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SegmentTrackerAPP.DataSet')),
                ('id_imagen_base', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SegmentTrackerAPP.Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='John', max_length=100)),
                ('apellido', models.CharField(default='Doe', max_length=100)),
                ('correo', models.CharField(default='jdoe@gmail.com', max_length=100)),
                ('institucion', models.CharField(default='Doe Institute', max_length=100)),
                ('password', models.CharField(default='123456', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='csvresult',
            name='idDataSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SegmentTrackerAPP.DataSet'),
        ),
        migrations.AddField(
            model_name='csvresult',
            name='id_imagen_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SegmentTrackerAPP.Imagen'),
        ),
    ]
