# Generated by Django 2.1.8 on 2019-04-19 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SegmentTrackerAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoresResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dir', models.CharField(default='dirImage', max_length=256)),
                ('name', models.CharField(default='nameImage', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date',
            field=models.DateField(default=datetime.date(2019, 4, 19), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='coloresresult',
            name='idDataSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SegmentTrackerAPP.DataSet'),
        ),
        migrations.AddField(
            model_name='coloresresult',
            name='id_imagen_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SegmentTrackerAPP.Imagen'),
        ),
    ]
