# Generated by Django 2.1.8 on 2019-04-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SegmentTrackerAPP', '0002_auto_20190419_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField(default=1)),
                ('y', models.IntegerField(default=1)),
                ('area', models.IntegerField(default=1)),
                ('num_celula', models.IntegerField(default=1)),
                ('idDataSet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SegmentTrackerAPP.DataSet')),
                ('id_imagen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SegmentTrackerAPP.Imagen')),
            ],
        ),
    ]
