# Generated by Django 2.1.8 on 2019-04-20 04:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SegmentTrackerAPP', '0003_celula'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenRastreo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dir', models.CharField(default='dirImage', max_length=256)),
                ('name', models.CharField(default='nameImage', max_length=256)),
                ('num_secuencia', models.IntegerField(default=1)),
                ('num_celula', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date',
            field=models.DateField(default=datetime.date(2019, 4, 20), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='imagenrastreo',
            name='idDataSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SegmentTrackerAPP.DataSet'),
        ),
    ]
